name: Gatsby Publish

on:
  push:
    branches: development

jobs:
  # selenium-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: setup python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8 #install the python needed
  #     - name: install python packages
  #       run: |
  #         python -m pip install selenium
  #     - name: install selenium
  #       uses: nanasess/setup-chromedriver@master
  #     - run: |
  #       export DISPLAY=:99
  #       chromedriver --url-base=/wd/hub &
  #       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

  #     - name: execute py script # run the run.py to get the latest data
  #           run: |
  #           python test.py
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --no-color
          deploy-branch: master
