name: Gatsby Publish

on:
  push:
    branches: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2.2.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --no-color
          deploy-branch: master
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install selenium
      - name: Prepare Chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Launch browser
        run: |
          google-chrome --version
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Run tests
        run: python test.py
